apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud
spec:
  replicas: {{ if eq .Release.Namespace "ms-onboarding-dev" }} {{ .Values.replicas.dev }}
       {{ else if eq .Release.Namespace "ms-onboarding-prod" }} {{ .Values.replicas.prod }}
  {{ end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: crud
  template: 
    metadata:
      labels:
        app: crud
    spec:
      containers:
      - name: crud
        image: "{{ .Values.image.repo}}/{{ .Values.image.name}}:{{ .Chart.AppVersion }}"
        ports:
          - name: http-port
            containerPort: 80